const audioBlock = {
  1: 'assets/audio/sonatikhao.mp3',
  2: 'assets/audio/Marareih.mp3',
  3: 'assets/audio/ConsonantnataVowels.mp3',
  4: 'assets/audio/Nuby_rei.mp3',
  5: 'assets/audio/Nuby_hluna.mp3',
  6: 'assets/audio/Ko.mp3',
  7: 'assets/audio/sonatikhao.mp3',
  8: 'assets/audio/Nubyreinadah.mp3',
  9: 'assets/audio/sonatikhao.mp3',
  10: 'assets/audio/Vowelparonsanadahnatangiana.mp3',
  11: 'assets/audio/sonatikhao.mp3',
  12: 'assets/audio/sonatikhao.mp3',
  13: 'assets/audio/sonatikhao.mp3',
  14: 'assets/audio/sonatikhao.mp3',
};
