const audioBlock = {
  1: 'assets/audio/1.mp3',
  2: 'assets/audio/Marareih.mp3',
  3: 'assets/audio/Vowel_Consonanats.mp3',
  4: 'assets/audio/Nuby_rei.mp3',
  5: 'assets/audio/Nuby_hluna.mp3',
  6: 'assets/audio/Ko.mp3',
  7: 'assets/audio/Relax.mp3',
  8: 'assets/audio/Nuby_reina.mp3',
  9: 'assets/audio/Nuby_reina.mp3',
  10: 'assets/audio/Nuby_reina.mp3',
  11: 'assets/audio/Nuby_reina.mp3',
  12: 'assets/audio/1.mp3',
  13: 'assets/audio/1.mp3',
};
