const topicList = [
  '1. MARA REIH CHÂHNAWH (ALPHABET)'
      '2. VOWELS NATA CONSONANTS'
      '3.	NUHBY REI NATA RO DÂH (1-100)'
      '4.	NUHBY HLUHNA LÂ REI NATA RO DÂH (1-10,00,00,00,000)'
      '5.	KÔ,THLA,HÂTA NATA NIHZY'
      '6.	MARAPA RÂH LIATA RÂHSA YPAZY'
      '7.	MARA CHIZY'
];
