name: mara_rei_achuna1
description: A new Flutter project.
publish_to: 'none'
version: 1.0.1+5

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter
  just_audio: ^0.9.34
  cupertino_icons: ^1.0.2
  google_fonts: ^5.1.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/image/mara_logo.jpg"

flutter:
  uses-material-design: true
  assets:
    - assets/audio/Ko.mp3
    - assets/audio/Marareih.mp3
    - assets/audio/Nuby_hluna.mp3
    - assets/audio/Nuby_rei.mp3
    - assets/audio/Nuby_reina.mp3
    - assets/audio/Vowel_Consonanats.mp3
    - assets/audio/1.mp3
    - assets/audio/Relax.mp3
    - assets/image/nubyh.png
    - assets/image/Contentsh.png 
    - assets/image/icon.png
    - assets/image/phohla.png
    - assets/image/MaraPh.png
    - assets/image/thyu.png
    - assets/image/cho.png
    - assets/image/MARAPHOPA1.png
    - assets/image/PHOHLA2.png
    - assets/image/HOME1.png
    - assets/image/ACHUAWPAZY.png


family: 'Raleway'
fonts:
  - asset: assets/fonts/Raleway-Regular.ttf
    weight: 400
  - asset: assets/fonts/Raleway-Bold.ttf
    weight: 700
