name: mara_rei_achuna1
description: A new Flutter project.
publish_to: 'none'
version: 2.0.1+10

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  google_nav_bar: ^5.0.6
  photo_view: ^0.15.0
  persistent_bottom_nav_bar: ^5.0.2
  image_picker: ^1.2.1
  get_it: ^7.7.0
  flutter_tts: ^4.0.2
  firebase_core: ^3.15.2
  just_audio: ^0.10.5
  cloud_firestore: ^5.6.12
  audioplayers: ^6.6.0
  firebase_auth: ^5.7.0
  firebase_storage: ^12.4.10
  provider: ^6.1.5+1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^4.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/image/mara_logo.jpg"

flutter:
  uses-material-design: true

  assets:
    - assets/audio/
    - assets/image/

  