name: mara_rei_achuna1
description: A new Flutter project.
publish_to: 'none'
version: 1.0.1+5

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter
  just_audio: ^0.9.34
  cupertino_icons: ^1.0.2
  google_fonts: ^5.1.0
  google_nav_bar: ^5.0.6
 
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/image/mara_logo.jpg"

flutter:
  uses-material-design: true
  assets:
    - assets/audio/Ko.mp3
    - assets/audio/Marareih.mp3
    - assets/audio/Nuby_hluna.mp3
    - assets/audio/Nuby_rei.mp3
    - assets/audio/Nuby_reina.mp3
    - assets/audio/ConsonantnataVowels.mp3
    - assets/audio/1.mp3
    - assets/audio/Relax.mp3
    - assets/image/nubyh.png
    - assets/image/Contentsfn.png 
    - assets/image/icon.png
    - assets/image/phohla.png
    - assets/image/MaraPh.png
    - assets/image/thyu.png
    - assets/image/cho.png
    - assets/image/MARAPHOPA1.png
    - assets/image/PHOHLA2.png
    - assets/image/HOME1.png
    - assets/image/ACHUAWPAZY.png
    - assets/image/2.png
    - assets/image/3.png
    - assets/image/5.jpg
    - assets/image/6.png
    - assets/image/10.jpg
    - assets/image/15.png
    - assets/image/19.png
    - assets/image/21.png
    - assets/image/23.png
    - assets/image/25.png
    - assets/image/28.png
    - assets/image/32.png
    - assets/image/36.png
    - assets/image/48.png
    - assets/image/75.png
    - assets/image/79.jpg
    - assets/image/AWKHYHLA.png
    - assets/image/AWKHYHLA1.png
    - assets/image/awkhypa.png
    - assets/image/90.png
    - assets/image/91.png
    - assets/image/92.png
    - assets/image/93.png
    - assets/image/94.png


family: 'Raleway'
fonts:
  - asset: assets/fonts/Raleway-Regular.ttf
    weight: 400
  - asset: assets/fonts/Raleway-Bold.ttf
    weight: 700
