const tluanaList = [
  '1. Mara Chhopasiana',
  '2. Mara chano nata chapaw atobi nata ama hrozie nôchâ',
  '3. Sawnah moh-chho',
  '4. Mara phôhpa azuapa chi',
  '5. Rieta nata Vachhuh Phôh',
  '6. Cha-U nata Sakhih Phôh',
  '7. Papangawh lyurie atlapa phôh',
  '8. Hâratiepa Phôhpa',
  '9. Sawku nata Sakhih Phôhpa',
  '10. Leidoh phôh',
  '11. Savai nata Chakeih Phôh',
  '12. Azyh Phôh',
  '13. Raih-no Phôh',
  '14.Chavyhpupa nata tla-uah Phôh',
  '15. Tlianô phôh',
  '16. Chheihluti unawh Phôh',
  '17. Nârâ Phôh',
  '18. Hlichhy nata hly-âh Phôh',
  '19. Liasarinô Phôh',
  '20. Hlyche nata amah-nô Phôhpa',
  '21. Siaramainô Phôh,',
  '22. Seramenô Phôhpa',
  '23. Karu nata Anô',
  '24. Azyh nata ahrupa nata asota Phôhpa',
  '25. Samieliethie Phôh',
  '26. Unawh pano maw nata chho lata asie penawh Phôhpa',
  '27. Haratiepa Phôhpa (Paku Chiachi pawnô Phôhpa)',
  '28. Vao nata i Phôhpa',
  '29. Pahmôpi Phôhpa',
  '30. Laidyu unawh nata pala tipo yna dâh ',
];
